parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     cantine
    database_user:     admin
    database_password: password

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    facebookAppId:  166783536688070
    facebookAppSecret:  76e62934b8423cf146ed9d4242f704a4
